name: CD

on:
  push:
    branches:
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.TOKEN_FOR_DOCKER }}" | docker login ghcr.io -u au2a --password-stdin

      - name: Build and push frontend image
        working-directory: ./Frontend
        run: |-
          docker build -t ghcr.io/docentre/docentre-frontend .
          docker push ghcr.io/docentre/docentre-frontend

      - name: Build and push OAuth image
        working-directory: ./OAuth
        run: |-
          docker build -t ghcr.io/docentre/docentre-oauth .
          docker push ghcr.io/docentre/docentre-oauth

  Kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Load kubeconfig
        run: |-
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode >> ~/.kube/config

      - name: Load k8s files
        run: |-
          mkdir k8s
          echo "${{ secrets.KUBE_FILE }}" | base64 --decode >> k8s/k8s.yaml

      - name: Stop old k8s
        working-directory: ./k8s
        run: |-
          kubectl delete -f .

      - name: Start k8s
        if: always()
        working-directory: ./k8s
        run: |-
          kubectl apply -f .
